### ISSUE TITLE
Voting system will polarise people/communities?

### ISSUE THREAD

**Issue by marcusnewton1** [MightyAlex200/Comet#17]
I'm concerned that the novel voting system is unnecessary, and would even produce undesirable behaviours. The assumption is that you will hate certain people and you 'obviously' won't like what they like. I suggest the default version of Comet to be simpler and allow this as a configurable option in the UI.

**Comment by MightyAlex200** [comment]
Comet is definitely going to have customizable KarmaMaps (e.g. count votes for everybody, count votes for people you like, count votes for your friends, etc.), but I'm not sure that making it disabled by default is the best thing. I think we could maximize the amount that everybody gets out of Comet by having some sort of wizard when you first open it/create an account that determines some settings.

**Comment by marcusnewton1** [comment]
Maybe it could be a simple toggle in a sidebar or settings dropdown, allowing users to quickly compare the two 'realities' and see what they prefer.
